# Regresión lineal

## Usando scikit-learn para regresión lineal y la seleccion de rasgos

El desarrollo del codigo para encontrar las variables optimas para generar el modelo de regresión lineal más eficiente a veces se torna tedioso, considerando que muchas veces tendremos innumerables variables, todo esto está pensado e implementado de manera rápida y eficaz en el paquete scikit-learn

In [3]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv("../datasets/ads/Advertising.csv")

In [10]:
feature_cols = data.columns[:3].values.tolist()

In [12]:
x= data[feature_cols]
y= data["Sales"]

In [14]:
estimator = SVR(kernel="linear")          # le indica que tipo de ajuste queremos realizar
# le indicamos el ajuste, la cantidad de parámetros finales y los pasos que queremos que haga el proceso
selector = RFE(estimator, 2, step=1)       
selector = selector.fit(x,y)             # le indicamos que haga el fiteo considerando los datos x e y 

In [16]:
selector.support_          # el resultado es un array indicando cuales son las varibles que se quedaron

array([ True,  True, False])

In [19]:
selector.ranking_          # las variables seleccionadas siempre aparecen en rankin 1 y dps en orden 
                           # descendente las demas

array([1, 1, 2])

### Ahora que sabemos las varibles que utilizaremos vamos por la regresion 

In [20]:
from sklearn.linear_model import LinearRegression

In [22]:
x_pred = x[["TV","Radio"]]   # estas son las variables que utilizaremos

In [23]:
lm = LinearRegression()
lm.fit(x_pred,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [27]:
lm.intercept_      # INTERCEPTO

2.9210999124051362

In [28]:
lm.coef_           # BETA 1 Y BETA 2

array([0.04575482, 0.18799423])

In [29]:
lm.score(x_pred,y)    # R^2

0.8971942610828956