## El  método de K-Means

In [9]:
import numpy as np
from scipy.cluster.vq import vq

In [12]:
np.random.seed(0)
data = np.random.random(90).reshape(30,3)
data

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985],
       [0.77815675, 0.87001215, 0.97861834],
       [0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329],
       [0.94466892, 0.52184832, 0.41466194],
       [0.26455561, 0.77423369, 0.45615033],
       [0.56843395, 0.0187898 , 0.6176355 ],
       [0.61209572, 0.616934  , 0.94374808],
       [0.6818203 , 0.3595079 , 0.43703195],
       [0.6976312 , 0.06022547, 0.66676672],
       [0.67063787, 0.21038256, 0.1289263 ],
       [0.31542835, 0.36371077, 0.57019677],
       [0.43860151, 0.98837384, 0.10204481],
       [0.20887676, 0.16130952, 0.65310833],
       [0.2532916 , 0.46631077, 0.24442559],
       [0.15896958, 0.11037514, 0.65632959],
       [0.13818295, 0.19658236, 0.36872517],
       [0.

In [13]:
##elegimos 2 centroides al azar de la muestra random creada, asumimos que nos pidieron un K=2
c1= np.random.choice(range(len(data)))
c2= np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1],data[c2]])
clust_centers

array([[0.56843395, 0.0187898 , 0.6176355 ],
       [0.11827443, 0.63992102, 0.14335329]])

In [16]:
vq(data,clust_centers)  ## nos genera los 2 clusters, basandose en los centroides que les dimos
                        ## además nos da en otro array las distancias al centro de su cluster

(array([1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
        0, 1, 0, 1, 0, 0, 0, 1], dtype=int32),
 array([0.63410319, 0.40653272, 0.91558599, 0.49193536, 0.53771137,
        0.527138  , 0.94808847, 0.52511165, 0.        , 0.66016581,
        0.37051325, 0.        , 0.68266554, 0.40194891, 0.1443008 ,
        0.53478043, 0.43038673, 0.47511598, 0.38839615, 0.24204497,
        0.42136228, 0.49773286, 0.34417309, 0.46858151, 0.724559  ,
        0.36649881, 0.41704075, 0.17727528, 0.26405256, 0.7889177 ]))

In [17]:
from scipy.cluster.vq import kmeans

In [18]:
kmeans(data,clust_centers)  ##kmeans usando baricentros

(array([[0.56348052, 0.29714776, 0.63538769],
        [0.2816683 , 0.68540989, 0.41660002]]),
 0.3870312858617991)

In [20]:
kmeans(data,2)       ## kmeans usando el n de clusters

(array([[0.40390442, 0.20120253, 0.51959404],
        [0.50429988, 0.73959556, 0.580191  ]]),
 0.37876772903598693)

**El array que entrega son las posiciones del baricentro (en este caso hicimos una rray 3d). El ultimo valor entrega el error**